### PR TITLE
feat: Add extra event codes to subscribe to

### PR DESCRIPTION
**Pull request by FrankZZ**
I've added some more event codes because the one I am using was missing.

### CODE REVIEW

**Comment by FrankZZ** [comment]
I see my editor also cleaned up some obsolete whitespaces

**Comment by kees24** [comment]
+1, CrossLineDetection and CrossRegionDetection would be a great help.

**Comment by DeadEnded** [comment]
Is that package-lock.json file necessary?
Seems like that might be an accidentally included file...
Anyway, I have found two more that I would like to add as well if this ever gets merged...
`SmartMotionHuman` and `SmartMotionVehicle`.

Not sure if this repo is being maintained though... might look to see if a fork is.

Cheers!
DeadEnd

**Comment by FrankZZ** [comment]
Hi DeadEnd,

Committing the package-lock file is common. This basically takes a snapshot of all the dependencies with their versions. 
If I say "it works on my machine" and you say it doesn't, it's possible due to a dependency version mismatch. package-lock tries to solve that problem.
https://docs.npmjs.com/configuring-npm/package-lock-json.html

also, i've added the two events you just mentioned!

**Comment by DeadEnded** [comment]
Thanks for the explanation and the added events.
It has been 2 years since anything was merged - are you maintaining your own fork?
My goal is to get `node-red-contrib-dahua-device` to have all these new events, but it is based on the fork 'inwaar/node-dahua-api'.

This has as well not been updating in a long time - but not sure if the maintainer is willing to change their dependency.
I might request it to a more updated for so we can get these events into Node-Red.

Thanks!
DeadEnd


edit:  I see you have already forked this project as well... so I assume that is exactly what you have done.
I'm guessing your nodes are in pallet manager by default?
I'm guessing there is a way to add custom nodes - I'll have to look it up - thanks!

**Comment by FrankZZ** [comment]
> edit: I see you have already forked this project as well... so I assume that is exactly what you have done.
> I'm guessing your nodes are in pallet manager by default?
> I'm guessing there is a way to add custom nodes - I'll have to look it up - thanks!

yep! that's what I've done, 
as to your last question: running `npm install FrankZZ/node-red-contrib-dahua-device` in your user data dir (default is `$HOME/.node-red`) in will fetch my fork from GitHub and install it
(be sure to remove inwaar's version first- they will probably collide otherwise)

**Comment by DeadEnded** [comment]
Yes, that was what I expected... I have only used pallet manager in the GUI (docker install).
So, I will have to attach to the container and install it manually.
Not a problem - was just wondering if there was a GUI way - I guess not.

Thanks again!

**Comment by DeadEnded** [comment]
hmm... got it installed and restarted and getting a syntax error:
```
SyntaxError: Invalid or unexpected token (line:1)
```
Unfortunately, I don't see anything else.
I tried to post an issue on your repo (so we don't flood this one) but it doesn't appear it is enabled.

**Comment by DeadEnded** [comment]
hmm... getting this error:
```
5 Oct 09:44:33 - [warn] [node-red-contrib-dahua-device/dahua-device] SyntaxError: Invalid or unexpected token (line:1),
```
Can't find much else in the logs yet... not sure what the cause of the problem is.
Again, I am running in Docker... but not sure how that would cause a problem since the original package worked... you only made a few small modifications as far as the Node-Red part...

Ok, I've uninstalled/restarted/installed and checked every log and avenue I can think of...
I can't figure out what I'm doing wrong, but your version keeps giving that error... nothing else is different...
Would really like to get this working, but I don't know what is wrong.

**Comment by FrankZZ** [comment]
> hmm... getting this error:
> 
> ```
> 5 Oct 09:44:33 - [warn] [node-red-contrib-dahua-device/dahua-device] SyntaxError: Invalid or unexpected token (line:1),
> ```
> 
> Can't find much else in the logs yet... not sure what the cause of the problem is.
> Again, I am running in Docker... but not sure how that would cause a problem since the original package worked... you only made a few small modifications as far as the Node-Red part...
> 
> Ok, I've uninstalled/restarted/installed and checked every log and avenue I can think of...
> I can't figure out what I'm doing wrong, but your version keeps giving that error... nothing else is different...
> Would really like to get this working, but I don't know what is wrong.

Fixed! Missing single quote

**Review by nayrnet — APPROVED** [review]
lgtm

**Comment by FrankZZ** [comment]
Thanks @nayrnet for merging! I had forgotten this PR is still open. I think I fixed the keepalive bug, which caused the script to lose connection after a while.

I plan on giving this project some more love, I might send some more PRs your way.
Thanks for starting this project!

**Comment by LeonardoBet92** [comment]
hi, I wanted to understand how I could export the Dahua node bees to directly read the data in a supervisor that manages Javascript, can you by any chance help me?

**Pull request merged**
